### ISSUE TITLE
Evaluation failed: TypeError: findRecap(...)[0].function is not a function

### ISSUE THREAD

**Issue by nicolaiwork** [Overmiind/Puppeteer-sharp-extra#3]
> PuppeteerSharp.EvaluationFailedException: 'Evaluation failed: TypeError: findRecap(...)[0].function is not a function
>   at __puppeteer_evaluation_script__:1:31'

First of all, thank you very much for this awesome tool! I was just looking for something like this.

This error happens when using the RecaptchaPlugin on a **recaptcha v2 invisible**. I have also tried to pull the latest changes but the same error.

I have attached a demo project.

[PuppeteerSharpExtraInvisCaptcha.zip](https://github.com/Overmiind/Puppeteer-sharp-extra/files/5402707/PuppeteerSharpExtraInvisCaptcha.zip)

**Comment by Telavian** [comment]
Do recaptcha v2 visible ones work for you? I tried the sample link https://patrickhlauke.github.io/recaptcha/ using the AntiCaptcha provider and was not able to get it working.

**Comment by nicolaiwork** [comment]
> Do recaptcha v2 visible ones work for you? I tried the sample link https://patrickhlauke.github.io/recaptcha/ using the AntiCaptcha provider and was not able to get it working.

Actually not. I get an "AntiCaptcha request ends with error - 0" error
This might have been fixed by this commit though https://github.com/Overmiind/Puppeteer-sharp-extra/commit/7426092fd118de6a235d898c7f3609d1dc5aee33

**Comment by Telavian** [comment]
Yes same error I received. I have not tested with latest.
In the mean time I switched to https://www.nuget.org/packages/AntiCaptchaAPI/ which seems to work fine.

**Comment by Overmiind** [comment]
I have the same problem and I am going to fix this in a couple of days. Thanks for your feedback

**Comment by Overmiind** [comment]
Fixed by #6 

I edited the ReCaptcha callback script and tried to use the plugin on this sites
https://recaptcha-demo.appspot.com/recaptcha-v2-invisible.php
https://www.google.com/recaptcha/api2/demo
https://recaptcha-demo.appspot.com/recaptcha-v2-checkbox-explicit.php 

The plugin doesn't work on this site - https://patrickhlauke.github.io/recaptcha/ because there are no submit buttons and captcha doesn't have a callback, so Recaptcha does nothing.  


If you will have another problem - please create a new issue
